spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auro?characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
greet:
  word: 嗨

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

# 配置端口
server:
  port: 8080

greeting:
  name: ss

---
# 开发配置
spring:
  profiles: dev

greeting:
  name: sylvan


---
# 生产配置
spring:
  profiles: prod

greeting:
  name: sisi
