/*
 * This file is generated by jOOQ.
 */
package com.sylvan.juno.persistence.jooq;

import com.sylvan.juno.persistence.jooq.tables.FlywaySchemaHistory;
import com.sylvan.juno.persistence.jooq.tables.GlobalLock;
import javax.annotation.Generated;

/** Convenience access to all tables in */
@Generated(
    value = {"http://www.jooq.org", "jOOQ version:3.11.12"},
    comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table <code>flyway_schema_history</code>. */
  public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY =
      com.sylvan.juno.persistence.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

  /** 全局锁表 */
  public static final GlobalLock GLOBAL_LOCK =
      com.sylvan.juno.persistence.jooq.tables.GlobalLock.GLOBAL_LOCK;
}
