// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/sylvan/auro/pkg/service/assoc/db/model/internal"
)

// Assoc is the golang structure for table assoc.
type Assoc internal.Assoc

// Fill with you ideas below.
