"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import ...common.v1.types_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AssocType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _AssocTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AssocType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ASSOC_TYPE_UNSPECIFIED: _AssocType.ValueType  # 0
    ASSOC_TYPE_TAGBY: _AssocType.ValueType  # 1
    """an object taged by a tag."""

    ASSOC_TYPE_TAGTO: _AssocType.ValueType  # 2
    """a tag taged to an object."""

    ASSOC_TYPE_CREATED_BY: _AssocType.ValueType  # 3
    """an object created by a user."""

    ASSOC_TYPE_CREATED_WITH: _AssocType.ValueType  # 4
    """a user created an object."""

    ASSOC_TYPE_INHERIT_FROM: _AssocType.ValueType  # 5
    """a child object inherit from parent object."""

    ASSOC_TYPE_EXTEND_TO: _AssocType.ValueType  # 6
    """an object extend to child object"""

    ASSOC_TYPE_FLOW_HISTORY: _AssocType.ValueType  # 7
    """an history version flow of itself, to_id is the version generated with timestamp."""

    ASSOC_TYPE_HISTORY_FLOW: _AssocType.ValueType  # 8
    """version of an flow, from_id is the generated by backend when an object has a new version, to_id is the id of this flow."""

class AssocType(_AssocType, metaclass=_AssocTypeEnumTypeWrapper):
    """type of association, type should be defined in pair, eg:
     ASSOC_TYPE_TAGBY = 1;
     ASSOC_TYPE_TAGTO = 2;
    """
    pass

ASSOC_TYPE_UNSPECIFIED: AssocType.ValueType  # 0
ASSOC_TYPE_TAGBY: AssocType.ValueType  # 1
"""an object taged by a tag."""

ASSOC_TYPE_TAGTO: AssocType.ValueType  # 2
"""a tag taged to an object."""

ASSOC_TYPE_CREATED_BY: AssocType.ValueType  # 3
"""an object created by a user."""

ASSOC_TYPE_CREATED_WITH: AssocType.ValueType  # 4
"""a user created an object."""

ASSOC_TYPE_INHERIT_FROM: AssocType.ValueType  # 5
"""a child object inherit from parent object."""

ASSOC_TYPE_EXTEND_TO: AssocType.ValueType  # 6
"""an object extend to child object"""

ASSOC_TYPE_FLOW_HISTORY: AssocType.ValueType  # 7
"""an history version flow of itself, to_id is the version generated with timestamp."""

ASSOC_TYPE_HISTORY_FLOW: AssocType.ValueType  # 8
"""version of an flow, from_id is the generated by backend when an object has a new version, to_id is the id of this flow."""

global___AssocType = AssocType


class CreateAssocRequest(google.protobuf.message.Message):
    """Request message for [AssocService.CreateAssoc][v1.AssocService.CreateAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    ASSOC_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Assoc's parent resource, if exists.
    Format : ``
    """

    @property
    def assoc(self) -> global___Assoc:
        """Required. The Assoc to create."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        assoc: typing.Optional[global___Assoc] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["assoc",b"assoc"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["assoc",b"assoc","parent",b"parent"]) -> None: ...
global___CreateAssocRequest = CreateAssocRequest

class CreateAssocResponse(google.protobuf.message.Message):
    """Response message for [AssocService.CreateAssoc][v1.AssocService.CreateAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___Assoc:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___Assoc] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___CreateAssocResponse = CreateAssocResponse

class UpdateAssocRequest(google.protobuf.message.Message):
    """Request message for [AssocService.UpdateAssoc][v1.AssocService.UpdateAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_ID_FIELD_NUMBER: builtins.int
    TO_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    ASSOC_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    from_id: builtins.int
    to_id: builtins.int
    a_type: global___AssocType.ValueType
    @property
    def assoc(self) -> global___Assoc: ...
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Required. The update mask applies to the resource.
        For the `FieldMask` definition, see [google.protobuf.FieldMask][google.protobuf.FieldMask].
        Updatable fields:

          * `id`
          * `update_at`
          * `create_at`
        """
        pass
    def __init__(self,
        *,
        from_id: builtins.int = ...,
        to_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        assoc: typing.Optional[global___Assoc] = ...,
        update_mask: typing.Optional[google.protobuf.field_mask_pb2.FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["assoc",b"assoc","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","assoc",b"assoc","from_id",b"from_id","to_id",b"to_id","update_mask",b"update_mask"]) -> None: ...
global___UpdateAssocRequest = UpdateAssocRequest

class UpdateAssocResponse(google.protobuf.message.Message):
    """Response message for [AssocService.UpdateAssoc][v1.AssocService.UpdateAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___Assoc:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___Assoc] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___UpdateAssocResponse = UpdateAssocResponse

class ListAssocsRequest(google.protobuf.message.Message):
    """Request message for [AssocService.ListAssocs][v1.AssocService.ListAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    COMMON_OPTION_FIELD_NUMBER: builtins.int
    COMMON_FILTER_FIELD_NUMBER: builtins.int
    READ_MASK_FIELD_NUMBER: builtins.int
    OPTION_FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Assoc's parent resource, if exists.
    Format : ``
    """

    @property
    def common_option(self) -> common.v1.types_pb2.CommonOption:
        """common list option."""
        pass
    @property
    def common_filter(self) -> common.v1.types_pb2.CommonFilter:
        """common list filter."""
        pass
    @property
    def read_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Mask specifying which fields to read."""
        pass
    @property
    def option_filter(self) -> global___AssocOptionFilter:
        """option filter struct for list Assoc."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        common_option: typing.Optional[common.v1.types_pb2.CommonOption] = ...,
        common_filter: typing.Optional[common.v1.types_pb2.CommonFilter] = ...,
        read_mask: typing.Optional[google.protobuf.field_mask_pb2.FieldMask] = ...,
        option_filter: typing.Optional[global___AssocOptionFilter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","common_option",b"common_option","option_filter",b"option_filter","read_mask",b"read_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","common_option",b"common_option","option_filter",b"option_filter","parent",b"parent","read_mask",b"read_mask"]) -> None: ...
global___ListAssocsRequest = ListAssocsRequest

class ListAssocsResponse(google.protobuf.message.Message):
    """Response message for [AssocService.ListAssocs][v1.AssocService.ListAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Details(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ITEMS_FIELD_NUMBER: builtins.int
        NEXT_REQUEST_FIELD_NUMBER: builtins.int
        TOTAL_COUNT_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Assoc]:
            """A list of Assocs that matches the specified filter in the request."""
            pass
        @property
        def next_request(self) -> global___ListAssocsRequest: ...
        total_count: builtins.int
        """total items count of this filter."""

        def __init__(self,
            *,
            items: typing.Optional[typing.Iterable[global___Assoc]] = ...,
            next_request: typing.Optional[global___ListAssocsRequest] = ...,
            total_count: builtins.int = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["next_request",b"next_request"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["items",b"items","next_request",b"next_request","total_count",b"total_count"]) -> None: ...

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___ListAssocsResponse.Details: ...
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___ListAssocsResponse.Details] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___ListAssocsResponse = ListAssocsResponse

class DeleteAssocRequest(google.protobuf.message.Message):
    """Request message for [AssocService.DeleteAssoc][v1.AssocService.DeleteAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_ID_FIELD_NUMBER: builtins.int
    TO_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    from_id: builtins.int
    to_id: builtins.int
    a_type: global___AssocType.ValueType
    def __init__(self,
        *,
        from_id: builtins.int = ...,
        to_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","from_id",b"from_id","to_id",b"to_id"]) -> None: ...
global___DeleteAssocRequest = DeleteAssocRequest

class DeleteAssocResponse(google.protobuf.message.Message):
    """Response message for [AssocService.DeleteAssoc][v1.AssocService.DeleteAssoc]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___Assoc:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___Assoc] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___DeleteAssocResponse = DeleteAssocResponse

class DeleteAssocsRequest(google.protobuf.message.Message):
    """Request message for [AssocService.DeleteAssocs][v1.AssocService.DeleteAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    COMMON_FILTER_FIELD_NUMBER: builtins.int
    OPTION_FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Assoc's parent resource, if exists.
    Format : ``
    """

    @property
    def common_filter(self) -> common.v1.types_pb2.CommonFilter:
        """use common filter to delete Assoc"""
        pass
    @property
    def option_filter(self) -> global___AssocOptionFilter:
        """option filter struct for delete Assoc items."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        common_filter: typing.Optional[common.v1.types_pb2.CommonFilter] = ...,
        option_filter: typing.Optional[global___AssocOptionFilter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","option_filter",b"option_filter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","option_filter",b"option_filter","parent",b"parent"]) -> None: ...
global___DeleteAssocsRequest = DeleteAssocsRequest

class DeleteAssocsResponse(google.protobuf.message.Message):
    """Response message for [AssocService.DeleteAssocs][v1.AssocService.DeleteAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """deleted id list."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___DeleteAssocsResponse = DeleteAssocsResponse

class CountAssocsRequest(google.protobuf.message.Message):
    """Request message for [AssocService.CountAssocs][v1.AssocService.CountAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    from_id: builtins.int
    a_type: global___AssocType.ValueType
    def __init__(self,
        *,
        from_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","from_id",b"from_id"]) -> None: ...
global___CountAssocsRequest = CountAssocsRequest

class CountAssocsResponse(google.protobuf.message.Message):
    """Response message for [AssocService.CountAssocs][v1.AssocService.CountAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    details: builtins.int
    """deleted id list."""

    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___CountAssocsResponse = CountAssocsResponse

class GetAssocRequest(google.protobuf.message.Message):
    """Request message for [AssocService.CountAssocs][v1.AssocService.CountAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    TO_ID_FIELD_NUMBER: builtins.int
    from_id: builtins.int
    a_type: global___AssocType.ValueType
    to_id: builtins.int
    def __init__(self,
        *,
        from_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        to_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","from_id",b"from_id","to_id",b"to_id"]) -> None: ...
global___GetAssocRequest = GetAssocRequest

class GetAssocResponse(google.protobuf.message.Message):
    """Response message for [AssocService.CountAssocs][v1.AssocService.CountAssocs]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___Assoc:
        """deleted id list."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___Assoc] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___GetAssocResponse = GetAssocResponse

class Assoc(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    CREATE_AT_FIELD_NUMBER: builtins.int
    UPDATE_AT_FIELD_NUMBER: builtins.int
    FROM_ID_FIELD_NUMBER: builtins.int
    TO_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    id: builtins.int
    """auto increase id."""

    create_at: typing.Text
    """Output only. Timestamp when this Dataset was created, convert to local timezone string."""

    update_at: typing.Text
    """Output only. Timestamp when this Dataset was last updated, convert to local timezone string."""

    from_id: builtins.int
    to_id: builtins.int
    a_type: global___AssocType.ValueType
    meta: typing.Text
    def __init__(self,
        *,
        id: builtins.int = ...,
        create_at: typing.Text = ...,
        update_at: typing.Text = ...,
        from_id: builtins.int = ...,
        to_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        meta: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","create_at",b"create_at","from_id",b"from_id","id",b"id","meta",b"meta","to_id",b"to_id","update_at",b"update_at"]) -> None: ...
global___Assoc = Assoc

class AssocOptionFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_ID_FIELD_NUMBER: builtins.int
    A_TYPE_FIELD_NUMBER: builtins.int
    TO_IDS_FIELD_NUMBER: builtins.int
    from_id: builtins.int
    a_type: global___AssocType.ValueType
    @property
    def to_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        from_id: builtins.int = ...,
        a_type: global___AssocType.ValueType = ...,
        to_ids: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_type",b"a_type","from_id",b"from_id","to_ids",b"to_ids"]) -> None: ...
global___AssocOptionFilter = AssocOptionFilter
