// Code generated by github.com/sylvan/auro/toolkits/cmd/gen-proto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: common/v1/types.proto

package commonv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code extends GRPC's code but maps to status 2XX in grpc-gateway.
// Check:
// definition:  https://github.com/grpc/grpc-go/blob/master/codes/codes.go,
// and mapping: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go.
type Code int32

const (
	Code_CODE_UNSPECIFIED Code = 0
	// For any unidentified error.
	Code_CODE_GENERAL_ERROR    Code = 1000
	Code_CODE_INVALID_ARGUMENT Code = 1003
	Code_CODE_NOT_FOUND        Code = 1005
	Code_CODE_ALREADY_EXISTS   Code = 1006
	// SQL errors. Should hide any detailed SQL message to prevent data breaches.
	// For any unidentified SQL error.
	Code_CODE_GENERAL_SQL_ERROR Code = 2000
	// Maps sql.ErrNoRows.
	Code_CODE_SQL_NO_ROWS Code = 2001
	// k8s errors.
	// For experiment  with k8s resource not enough.
	Code_CODE_K8S_NOT_ENOUGH_RESOURCE Code = 3000
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:    "CODE_UNSPECIFIED",
		1000: "CODE_GENERAL_ERROR",
		1003: "CODE_INVALID_ARGUMENT",
		1005: "CODE_NOT_FOUND",
		1006: "CODE_ALREADY_EXISTS",
		2000: "CODE_GENERAL_SQL_ERROR",
		2001: "CODE_SQL_NO_ROWS",
		3000: "CODE_K8S_NOT_ENOUGH_RESOURCE",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED":             0,
		"CODE_GENERAL_ERROR":           1000,
		"CODE_INVALID_ARGUMENT":        1003,
		"CODE_NOT_FOUND":               1005,
		"CODE_ALREADY_EXISTS":          1006,
		"CODE_GENERAL_SQL_ERROR":       2000,
		"CODE_SQL_NO_ROWS":             2001,
		"CODE_K8S_NOT_ENOUGH_RESOURCE": 3000,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details *anypb.Any `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

// option struct for list.
type CommonOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The standard page number, start with zero, use cursor or size as page rotation.
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// The standard list page size.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// The standard list page cursor.
	Cursor string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// The search keyword.
	Query string `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	// A comma-separated list of fields to order by, sorted in descending order.
	// Supported fields example:
	//   * `create_at`
	//   * `update_at`
	OrderBy string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// A comma-separated list of fields to group by.
	GroupBy string `protobuf:"bytes,6,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
}

func (x *CommonOption) Reset() {
	*x = CommonOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonOption) ProtoMessage() {}

func (x *CommonOption) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonOption.ProtoReflect.Descriptor instead.
func (*CommonOption) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *CommonOption) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommonOption) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CommonOption) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CommonOption) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CommonOption) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *CommonOption) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

// filter struct for list.
type CommonFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnName string `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// High time string in local timezone, `${column_name}` <= '${high_time}'.
	HighTime string `protobuf:"bytes,2,opt,name=high_time,json=highTime,proto3" json:"high_time,omitempty"`
	// Low time string in local timezone `${column_name}` > '${low_time}'.
	LowTime string `protobuf:"bytes,3,opt,name=low_time,json=lowTime,proto3" json:"low_time,omitempty"`
	// exclude ids for next filter.
	// next filter will reset high_time with the lower time in current respone,
	// so, exclude_ids will be setted with the id that has timestamp ot this filter.
	ExcludeIds []int64 `protobuf:"varint,4,rep,packed,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"`
	// list object that id in include in this field.
	IncludeIds []int64 `protobuf:"varint,5,rep,packed,name=include_ids,json=includeIds,proto3" json:"include_ids,omitempty"`
}

func (x *CommonFilter) Reset() {
	*x = CommonFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonFilter) ProtoMessage() {}

func (x *CommonFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonFilter.ProtoReflect.Descriptor instead.
func (*CommonFilter) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *CommonFilter) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *CommonFilter) GetHighTime() string {
	if x != nil {
		return x.HighTime
	}
	return ""
}

func (x *CommonFilter) GetLowTime() string {
	if x != nil {
		return x.LowTime
	}
	return ""
}

func (x *CommonFilter) GetExcludeIds() []int64 {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

func (x *CommonFilter) GetIncludeIds() []int64 {
	if x != nil {
		return x.IncludeIds
	}
	return nil
}

var File_common_v1_types_proto protoreflect.FileDescriptor

var file_common_v1_types_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x79, 0x22, 0xa9, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x69, 0x67, 0x68, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x49, 0x64, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x49, 0x64, 0x73,
	0x2a, 0xd7, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x12, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x4c, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xe8, 0x07, 0x12, 0x1a, 0x0a, 0x15, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0xeb, 0x07, 0x12, 0x13, 0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xed, 0x07, 0x12, 0x18, 0x0a, 0x13, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53,
	0x10, 0xee, 0x07, 0x12, 0x1b, 0x0a, 0x16, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x47, 0x45, 0x4e, 0x45,
	0x52, 0x41, 0x4c, 0x5f, 0x53, 0x51, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xd0, 0x0f,
	0x12, 0x15, 0x0a, 0x10, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x51, 0x4c, 0x5f, 0x4e, 0x4f, 0x5f,
	0x52, 0x4f, 0x57, 0x53, 0x10, 0xd1, 0x0f, 0x12, 0x21, 0x0a, 0x1c, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x4b, 0x38, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x4e, 0x4f, 0x55, 0x47, 0x48, 0x5f, 0x52,
	0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0xb8, 0x17, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6c, 0x76, 0x61, 0x6e, 0x2f,
	0x61, 0x75, 0x72, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_types_proto_rawDescOnce sync.Once
	file_common_v1_types_proto_rawDescData = file_common_v1_types_proto_rawDesc
)

func file_common_v1_types_proto_rawDescGZIP() []byte {
	file_common_v1_types_proto_rawDescOnce.Do(func() {
		file_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_types_proto_rawDescData)
	})
	return file_common_v1_types_proto_rawDescData
}

var file_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_types_proto_goTypes = []interface{}{
	(Code)(0),            // 0: common.v1.Code
	(*Response)(nil),     // 1: common.v1.Response
	(*CommonOption)(nil), // 2: common.v1.CommonOption
	(*CommonFilter)(nil), // 3: common.v1.CommonFilter
	(*anypb.Any)(nil),    // 4: google.protobuf.Any
}
var file_common_v1_types_proto_depIdxs = []int32{
	4, // 0: common.v1.Response.details:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_types_proto_init() }
func file_common_v1_types_proto_init() {
	if File_common_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_types_proto_goTypes,
		DependencyIndexes: file_common_v1_types_proto_depIdxs,
		EnumInfos:         file_common_v1_types_proto_enumTypes,
		MessageInfos:      file_common_v1_types_proto_msgTypes,
	}.Build()
	File_common_v1_types_proto = out.File
	file_common_v1_types_proto_rawDesc = nil
	file_common_v1_types_proto_goTypes = nil
	file_common_v1_types_proto_depIdxs = nil
}
