name: Pull request CI

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: {replacement}
      credentials:
        username: ${{ github.actor }}
        # repository.secrets.name
        password: ${{ secrets.CI_ACTION }}
    steps:
    - uses: actions/checkout@v3
    - name: CI process
      run: |
        ls /.dockerenv && echo Found dockerenv && \
        make -C {model_name} build
