// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/sylvan/auro/pkg/service/echo/db/model/internal"
)

// Greeting is the golang structure for table greeting.
type Greeting internal.Greeting

// Fill with you ideas below.
