// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GreetingDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GreetingDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns greetingColumns // Columns contains all the columns of Table that for convenient usage.
}

// GreetingColumns defines and stores column names for table greeting.
type greetingColumns struct {
	Id       string // 自增ID，主键
	CreateAt string // 创建时间
	UpdateAt string // 更新时间
	Entity   string // greeting proto 结构内数据
	Greeted  string // proto 中的字段，直接映射出来做 index 使用
}

func NewGreetingDao() *GreetingDao {
	return &GreetingDao{
		M:     g.DB("echo").Model("greeting").Safe(),
		DB:    g.DB("echo"),
		Table: "greeting",
		Columns: greetingColumns{
			Id:       "id",
			CreateAt: "create_at",
			UpdateAt: "update_at",
			Entity:   "entity",
			Greeted:  "greeted",
		},
	}
}
