/*
 * This file is generated by jOOQ.
 */
package com.sylvan.juno.persistence.jooq.tables.pojos;

import java.io.Serializable;
import javax.annotation.Generated;

/** 全局锁表 */
@Generated(
    value = {"http://www.jooq.org", "jOOQ version:3.11.12"},
    comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GlobalLockDO implements Serializable {

  private static final long serialVersionUID = 1789901504;

  private final Integer id;
  private final String key;
  private final String holder;
  private final Long expireMs;
  private final Long createdAt;
  private final Long updatedAt;

  public GlobalLockDO(GlobalLockDO value) {
    this.id = value.id;
    this.key = value.key;
    this.holder = value.holder;
    this.expireMs = value.expireMs;
    this.createdAt = value.createdAt;
    this.updatedAt = value.updatedAt;
  }

  public GlobalLockDO(
      Integer id, String key, String holder, Long expireMs, Long createdAt, Long updatedAt) {
    this.id = id;
    this.key = key;
    this.holder = holder;
    this.expireMs = expireMs;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public Integer getId() {
    return this.id;
  }

  public String getKey() {
    return this.key;
  }

  public String getHolder() {
    return this.holder;
  }

  public Long getExpireMs() {
    return this.expireMs;
  }

  public Long getCreatedAt() {
    return this.createdAt;
  }

  public Long getUpdatedAt() {
    return this.updatedAt;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GlobalLockDO (");

    sb.append(id);
    sb.append(", ").append(key);
    sb.append(", ").append(holder);
    sb.append(", ").append(expireMs);
    sb.append(", ").append(createdAt);
    sb.append(", ").append(updatedAt);

    sb.append(")");
    return sb.toString();
  }
}
