// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sylvan/auro/pkg/service/assoc/db/dao/internal"
)

// assocDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type assocDao struct {
	*internal.AssocDao
}

var (
	// Assoc is globally public accessible object for table assoc operations.
	Assoc assocDao
)

func init() {
	Assoc = assocDao{
		internal.NewAssocDao(),
	}
}

// Fill with you ideas below.
