// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sylvan/auro/pkg/service/echo/db/dao/internal"
)

// greetingDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type greetingDao struct {
	*internal.GreetingDao
}

var (
	// Greeting is globally public accessible object for table greeting operations.
	Greeting greetingDao
)

func init() {
	Greeting = greetingDao{
		internal.NewGreetingDao(),
	}
}

// Fill with you ideas below.
