# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/v1/types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/types.proto\x12\tcommon.v1\x1a\x19google/protobuf/any.proto\"h\n\x08Response\x12\x12\n\x04\x63ode\x18\x01 \x01(\x05R\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12.\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyR\x07\x64\x65tails\"\x9a\x01\n\x0c\x43ommonOption\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n\x06\x63ursor\x18\x03 \x01(\tR\x06\x63ursor\x12\x14\n\x05query\x18\x04 \x01(\tR\x05query\x12\x19\n\x08order_by\x18\x05 \x01(\tR\x07orderBy\x12\x19\n\x08group_by\x18\x06 \x01(\tR\x07groupBy\"\xa9\x01\n\x0c\x43ommonFilter\x12\x1f\n\x0b\x63olumn_name\x18\x01 \x01(\tR\ncolumnName\x12\x1b\n\thigh_time\x18\x02 \x01(\tR\x08highTime\x12\x19\n\x08low_time\x18\x03 \x01(\tR\x07lowTime\x12\x1f\n\x0b\x65xclude_ids\x18\x04 \x03(\x03R\nexcludeIds\x12\x1f\n\x0binclude_ids\x18\x05 \x03(\x03R\nincludeIds*\xd7\x01\n\x04\x43ode\x12\x14\n\x10\x43ODE_UNSPECIFIED\x10\x00\x12\x17\n\x12\x43ODE_GENERAL_ERROR\x10\xe8\x07\x12\x1a\n\x15\x43ODE_INVALID_ARGUMENT\x10\xeb\x07\x12\x13\n\x0e\x43ODE_NOT_FOUND\x10\xed\x07\x12\x18\n\x13\x43ODE_ALREADY_EXISTS\x10\xee\x07\x12\x1b\n\x16\x43ODE_GENERAL_SQL_ERROR\x10\xd0\x0f\x12\x15\n\x10\x43ODE_SQL_NO_ROWS\x10\xd1\x0f\x12!\n\x1c\x43ODE_K8S_NOT_ENOUGH_RESOURCE\x10\xb8\x17\x42\x30Z.github.com/sylvan/auro/apis/common/v1;commonv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/sylvan/auro/apis/common/v1;commonv1'
  _CODE._serialized_start=499
  _CODE._serialized_end=714
  _RESPONSE._serialized_start=63
  _RESPONSE._serialized_end=167
  _COMMONOPTION._serialized_start=170
  _COMMONOPTION._serialized_end=324
  _COMMONFILTER._serialized_start=327
  _COMMONFILTER._serialized_end=496
# @@protoc_insertion_point(module_scope)
