// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: echo/v1/greeting.proto

package echov1

import (
	reflect "reflect"
	sync "sync"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	greeting "github.com/sylvan/auro/apis/thirdparty/greeting"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greeting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// auto increase id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Output only. Timestamp when this Dataset was created, convert to local timezone string.
	CreateAt string `protobuf:"bytes,2,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	// Output only. Timestamp when this Dataset was last updated, convert to local timezone string.
	UpdateAt string         `protobuf:"bytes,3,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Greeted  string         `protobuf:"bytes,4,opt,name=greeted,proto3" json:"greeted,omitempty"`
	Chat     *greeting.Chat `protobuf:"bytes,5,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *Greeting) Reset() {
	*x = Greeting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_echo_v1_greeting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeting) ProtoMessage() {}

func (x *Greeting) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_greeting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeting.ProtoReflect.Descriptor instead.
func (*Greeting) Descriptor() ([]byte, []int) {
	return file_echo_v1_greeting_proto_rawDescGZIP(), []int{0}
}

func (x *Greeting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Greeting) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Greeting) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

func (x *Greeting) GetGreeted() string {
	if x != nil {
		return x.Greeted
	}
	return ""
}

func (x *Greeting) GetChat() *greeting.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GreetingOptionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GreetingOptionFilter) Reset() {
	*x = GreetingOptionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_echo_v1_greeting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingOptionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingOptionFilter) ProtoMessage() {}

func (x *GreetingOptionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_greeting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingOptionFilter.ProtoReflect.Descriptor instead.
func (*GreetingOptionFilter) Descriptor() ([]byte, []int) {
	return file_echo_v1_greeting_proto_rawDescGZIP(), []int{1}
}

type ImportGreetingConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *ImportGreetingConfig) Reset() {
	*x = ImportGreetingConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_echo_v1_greeting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportGreetingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGreetingConfig) ProtoMessage() {}

func (x *ImportGreetingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_greeting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGreetingConfig.ProtoReflect.Descriptor instead.
func (*ImportGreetingConfig) Descriptor() ([]byte, []int) {
	return file_echo_v1_greeting_proto_rawDescGZIP(), []int{2}
}

func (x *ImportGreetingConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ExportGreetingConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *ExportGreetingConfig) Reset() {
	*x = ExportGreetingConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_echo_v1_greeting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportGreetingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGreetingConfig) ProtoMessage() {}

func (x *ExportGreetingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_greeting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGreetingConfig.ProtoReflect.Descriptor instead.
func (*ExportGreetingConfig) Descriptor() ([]byte, []int) {
	return file_echo_v1_greeting_proto_rawDescGZIP(), []int{3}
}

func (x *ExportGreetingConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_echo_v1_greeting_proto protoreflect.FileDescriptor

var file_echo_v1_greeting_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76,
	0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x74, 0x68,
	0x69, 0x72, 0x64, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a,
	0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x64, 0x12, 0x2d, 0x0a,
	0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x68,
	0x69, 0x72, 0x64, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x3a, 0x45, 0xea, 0x41,
	0x42, 0x0a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x79,
	0x6c, 0x76, 0x61, 0x6e, 0x2e, 0x61, 0x75, 0x72, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x65,
	0x63, 0x68, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x14, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x33, 0x0a, 0x14, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6c, 0x76, 0x61, 0x6e, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x73, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x63, 0x68,
	0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_echo_v1_greeting_proto_rawDescOnce sync.Once
	file_echo_v1_greeting_proto_rawDescData = file_echo_v1_greeting_proto_rawDesc
)

func file_echo_v1_greeting_proto_rawDescGZIP() []byte {
	file_echo_v1_greeting_proto_rawDescOnce.Do(func() {
		file_echo_v1_greeting_proto_rawDescData = protoimpl.X.CompressGZIP(file_echo_v1_greeting_proto_rawDescData)
	})
	return file_echo_v1_greeting_proto_rawDescData
}

var file_echo_v1_greeting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_echo_v1_greeting_proto_goTypes = []interface{}{
	(*Greeting)(nil),             // 0: echo.v1.Greeting
	(*GreetingOptionFilter)(nil), // 1: echo.v1.GreetingOptionFilter
	(*ImportGreetingConfig)(nil), // 2: echo.v1.ImportGreetingConfig
	(*ExportGreetingConfig)(nil), // 3: echo.v1.ExportGreetingConfig
	(*greeting.Chat)(nil),        // 4: thirdparty.greeting.Chat
}
var file_echo_v1_greeting_proto_depIdxs = []int32{
	4, // 0: echo.v1.Greeting.chat:type_name -> thirdparty.greeting.Chat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_echo_v1_greeting_proto_init() }
func file_echo_v1_greeting_proto_init() {
	if File_echo_v1_greeting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_echo_v1_greeting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_echo_v1_greeting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingOptionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_echo_v1_greeting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportGreetingConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_echo_v1_greeting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportGreetingConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_echo_v1_greeting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_v1_greeting_proto_goTypes,
		DependencyIndexes: file_echo_v1_greeting_proto_depIdxs,
		MessageInfos:      file_echo_v1_greeting_proto_msgTypes,
	}.Build()
	File_echo_v1_greeting_proto = out.File
	file_echo_v1_greeting_proto_rawDesc = nil
	file_echo_v1_greeting_proto_goTypes = nil
	file_echo_v1_greeting_proto_depIdxs = nil
}
