"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import ...thirdparty.greeting.chat_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Greeting(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    CREATE_AT_FIELD_NUMBER: builtins.int
    UPDATE_AT_FIELD_NUMBER: builtins.int
    GREETED_FIELD_NUMBER: builtins.int
    CHAT_FIELD_NUMBER: builtins.int
    id: builtins.int
    """auto increase id."""

    create_at: typing.Text
    """Output only. Timestamp when this Dataset was created, convert to local timezone string."""

    update_at: typing.Text
    """Output only. Timestamp when this Dataset was last updated, convert to local timezone string."""

    greeted: typing.Text
    @property
    def chat(self) -> thirdparty.greeting.chat_pb2.Chat: ...
    def __init__(self,
        *,
        id: builtins.int = ...,
        create_at: typing.Text = ...,
        update_at: typing.Text = ...,
        greeted: typing.Text = ...,
        chat: typing.Optional[thirdparty.greeting.chat_pb2.Chat] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chat",b"chat"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chat",b"chat","create_at",b"create_at","greeted",b"greeted","id",b"id","update_at",b"update_at"]) -> None: ...
global___Greeting = Greeting

class GreetingOptionFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___GreetingOptionFilter = GreetingOptionFilter

class ImportGreetingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_PATH_FIELD_NUMBER: builtins.int
    file_path: typing.Text
    def __init__(self,
        *,
        file_path: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["file_path",b"file_path"]) -> None: ...
global___ImportGreetingConfig = ImportGreetingConfig

class ExportGreetingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_PATH_FIELD_NUMBER: builtins.int
    file_path: typing.Text
    def __init__(self,
        *,
        file_path: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["file_path",b"file_path"]) -> None: ...
global___ExportGreetingConfig = ExportGreetingConfig
