"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import ...common.v1.types_pb2
import ...echo.v1.greeting_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CreateGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.CreateGreeting][v1.GreetingService.CreateGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    GREETING_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def greeting(self) -> echo.v1.greeting_pb2.Greeting:
        """Required. The Greeting to create."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        greeting: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["greeting",b"greeting"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeting",b"greeting","parent",b"parent"]) -> None: ...
global___CreateGreetingRequest = CreateGreetingRequest

class CreateGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.CreateGreeting][v1.GreetingService.CreateGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> echo.v1.greeting_pb2.Greeting:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___CreateGreetingResponse = CreateGreetingResponse

class GetGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.GetGreeting][v1.GreetingService.GetGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    READ_MASK_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    id: builtins.int
    """Required. The id of the Greeting in database."""

    @property
    def read_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Mask specifying which fields to read."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        id: builtins.int = ...,
        read_mask: typing.Optional[google.protobuf.field_mask_pb2.FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["read_mask",b"read_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","parent",b"parent","read_mask",b"read_mask"]) -> None: ...
global___GetGreetingRequest = GetGreetingRequest

class GetGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.GetGreeting][v1.GreetingService.GetGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> echo.v1.greeting_pb2.Greeting:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___GetGreetingResponse = GetGreetingResponse

class UpdateGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.UpdateGreeting][v1.GreetingService.UpdateGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    GREETING_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def greeting(self) -> echo.v1.greeting_pb2.Greeting:
        """Required. The Greeting which replaces the resource on the server."""
        pass
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Required. The update mask applies to the resource.
        For the `FieldMask` definition, see [google.protobuf.FieldMask][google.protobuf.FieldMask].
        Updatable fields:

          * `id`
          * `update_at`
          * `create_at`
        """
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        greeting: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        update_mask: typing.Optional[google.protobuf.field_mask_pb2.FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["greeting",b"greeting","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["greeting",b"greeting","parent",b"parent","update_mask",b"update_mask"]) -> None: ...
global___UpdateGreetingRequest = UpdateGreetingRequest

class UpdateGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.UpdateGreeting][v1.GreetingService.UpdateGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> echo.v1.greeting_pb2.Greeting:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___UpdateGreetingResponse = UpdateGreetingResponse

class ListGreetingsRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.ListGreetings][v1.GreetingService.ListGreetings]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    COMMON_OPTION_FIELD_NUMBER: builtins.int
    COMMON_FILTER_FIELD_NUMBER: builtins.int
    READ_MASK_FIELD_NUMBER: builtins.int
    OPTION_FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def common_option(self) -> common.v1.types_pb2.CommonOption:
        """common list option."""
        pass
    @property
    def common_filter(self) -> common.v1.types_pb2.CommonFilter:
        """common list filter."""
        pass
    @property
    def read_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Mask specifying which fields to read."""
        pass
    @property
    def option_filter(self) -> echo.v1.greeting_pb2.GreetingOptionFilter:
        """option filter struct for list Greeting."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        common_option: typing.Optional[common.v1.types_pb2.CommonOption] = ...,
        common_filter: typing.Optional[common.v1.types_pb2.CommonFilter] = ...,
        read_mask: typing.Optional[google.protobuf.field_mask_pb2.FieldMask] = ...,
        option_filter: typing.Optional[echo.v1.greeting_pb2.GreetingOptionFilter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","common_option",b"common_option","option_filter",b"option_filter","read_mask",b"read_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","common_option",b"common_option","option_filter",b"option_filter","parent",b"parent","read_mask",b"read_mask"]) -> None: ...
global___ListGreetingsRequest = ListGreetingsRequest

class ListGreetingsResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.ListGreetings][v1.GreetingService.ListGreetings]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Details(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ITEMS_FIELD_NUMBER: builtins.int
        NEXT_REQUEST_FIELD_NUMBER: builtins.int
        TOTAL_COUNT_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[echo.v1.greeting_pb2.Greeting]:
            """A list of Greetings that matches the specified filter in the request."""
            pass
        @property
        def next_request(self) -> global___ListGreetingsRequest:
            """next request."""
            pass
        total_count: builtins.int
        """total items count of this filter."""

        def __init__(self,
            *,
            items: typing.Optional[typing.Iterable[echo.v1.greeting_pb2.Greeting]] = ...,
            next_request: typing.Optional[global___ListGreetingsRequest] = ...,
            total_count: builtins.int = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["next_request",b"next_request"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["items",b"items","next_request",b"next_request","total_count",b"total_count"]) -> None: ...

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> global___ListGreetingsResponse.Details: ...
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[global___ListGreetingsResponse.Details] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___ListGreetingsResponse = ListGreetingsResponse

class DeleteGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.DeleteGreeting][v1.GreetingService.DeleteGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    id: builtins.int
    """Required. The resource name of the Greeting to delete.
    Format:
    `echos/greetings/{id}`
    """

    def __init__(self,
        *,
        parent: typing.Text = ...,
        id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","parent",b"parent"]) -> None: ...
global___DeleteGreetingRequest = DeleteGreetingRequest

class DeleteGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.DeleteGreeting][v1.GreetingService.DeleteGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> echo.v1.greeting_pb2.Greeting:
        """response data."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[echo.v1.greeting_pb2.Greeting] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___DeleteGreetingResponse = DeleteGreetingResponse

class DeleteGreetingsRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.DeleteGreetings][v1.GreetingService.DeleteGreetings]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    COMMON_FILTER_FIELD_NUMBER: builtins.int
    OPTION_FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def common_filter(self) -> common.v1.types_pb2.CommonFilter:
        """use common filter to delete Greeting"""
        pass
    @property
    def option_filter(self) -> echo.v1.greeting_pb2.GreetingOptionFilter:
        """option filter struct for delete Greeting items."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        common_filter: typing.Optional[common.v1.types_pb2.CommonFilter] = ...,
        option_filter: typing.Optional[echo.v1.greeting_pb2.GreetingOptionFilter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","option_filter",b"option_filter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["common_filter",b"common_filter","option_filter",b"option_filter","parent",b"parent"]) -> None: ...
global___DeleteGreetingsRequest = DeleteGreetingsRequest

class DeleteGreetingsResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.DeleteGreetings][v1.GreetingService.DeleteGreetings]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """deleted id list."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___DeleteGreetingsResponse = DeleteGreetingsResponse

class ImportGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.ImportGreeting][v1.GreetingService.ImportGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    IMPORT_CONFIG_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def import_config(self) -> echo.v1.greeting_pb2.ImportGreetingConfig:
        """Required. The desired input configs. The contents of all input configs will be
        imported in one batch.
        """
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        import_config: typing.Optional[echo.v1.greeting_pb2.ImportGreetingConfig] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["import_config",b"import_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["import_config",b"import_config","parent",b"parent"]) -> None: ...
global___ImportGreetingRequest = ImportGreetingRequest

class ImportGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.ImportGreeting][v1.GreetingService.ImportGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    details: builtins.bool
    """success or fail."""

    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___ImportGreetingResponse = ImportGreetingResponse

class ExportGreetingRequest(google.protobuf.message.Message):
    """Request message for [GreetingService.ExportGreeting][v1.GreetingService.ExportGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    EXPORT_CONFIG_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """The path of the Greeting's parent resource, if exists.
    Format: `echos`
    """

    @property
    def export_config(self) -> echo.v1.greeting_pb2.ExportGreetingConfig:
        """Required. The desired output location."""
        pass
    def __init__(self,
        *,
        parent: typing.Text = ...,
        export_config: typing.Optional[echo.v1.greeting_pb2.ExportGreetingConfig] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["export_config",b"export_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["export_config",b"export_config","parent",b"parent"]) -> None: ...
global___ExportGreetingRequest = ExportGreetingRequest

class ExportGreetingResponse(google.protobuf.message.Message):
    """Response message for [GreetingService.ExportGreeting][v1.GreetingService.ExportGreeting]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.int
    """status code."""

    message: typing.Text
    """error message."""

    @property
    def details(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """All of the files that are exported in this export operation."""
        pass
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        details: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","details",b"details","message",b"message"]) -> None: ...
global___ExportGreetingResponse = ExportGreetingResponse
