# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/v1/greeting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from ...thirdparty.greeting import chat_pb2 as thirdparty_dot_greeting_dot_chat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65\x63ho/v1/greeting.proto\x12\x07\x65\x63ho.v1\x1a\x19google/api/resource.proto\x1a\x1ethirdparty/greeting/chat.proto\"\xe4\x01\n\x08Greeting\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n\tcreate_at\x18\x02 \x01(\tR\x08\x63reateAt\x12\x1b\n\tupdate_at\x18\x03 \x01(\tR\x08updateAt\x12\x18\n\x07greeted\x18\x04 \x01(\tR\x07greeted\x12-\n\x04\x63hat\x18\x05 \x01(\x0b\x32\x19.thirdparty.greeting.ChatR\x04\x63hat:E\xea\x41\x42\n*github.com.sylvan.auro.apis/GreetingEntity\x12\x14\x65\x63hos/greetings/{id}\"\x16\n\x14GreetingOptionFilter\"3\n\x14ImportGreetingConfig\x12\x1b\n\tfile_path\x18\x01 \x01(\tR\x08\x66ilePath\"3\n\x14\x45xportGreetingConfig\x12\x1b\n\tfile_path\x18\x01 \x01(\tR\x08\x66ilePathB,Z*github.com/sylvan/auro/apis/echo/v1;echov1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo.v1.greeting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/sylvan/auro/apis/echo/v1;echov1'
  _GREETING._options = None
  _GREETING._serialized_options = b'\352AB\n*github.com.sylvan.auro.apis/GreetingEntity\022\024echos/greetings/{id}'
  _GREETING._serialized_start=95
  _GREETING._serialized_end=323
  _GREETINGOPTIONFILTER._serialized_start=325
  _GREETINGOPTIONFILTER._serialized_end=347
  _IMPORTGREETINGCONFIG._serialized_start=349
  _IMPORTGREETINGCONFIG._serialized_end=400
  _EXPORTGREETINGCONFIG._serialized_start=402
  _EXPORTGREETINGCONFIG._serialized_end=453
# @@protoc_insertion_point(module_scope)
