/*
 * This file is generated by jOOQ.
 */
package com.sylvan.hecate.persistence.jooq;

import com.sylvan.hecate.persistence.jooq.tables.FlywaySchemaHistory;
import com.sylvan.hecate.persistence.jooq.tables.GlobalLock;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/** This class is generated by jOOQ. */
@Generated(
    value = {"http://www.jooq.org", "jOOQ version:3.11.12"},
    comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = -63802306;

  /** The reference instance of <code></code> */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /** The table <code>flyway_schema_history</code>. */
  public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY =
      com.sylvan.hecate.persistence.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

  /** 全局锁表 */
  public final GlobalLock GLOBAL_LOCK =
      com.sylvan.hecate.persistence.jooq.tables.GlobalLock.GLOBAL_LOCK;

  /** No further instances allowed */
  private DefaultSchema() {
    super("", null);
  }

  /** {@inheritDoc} */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, GlobalLock.GLOBAL_LOCK);
  }
}
