/*
 * This file is generated by jOOQ.
 */
package com.sylvan.hecate.persistence.jooq;

import com.sylvan.hecate.persistence.jooq.tables.FlywaySchemaHistory;
import com.sylvan.hecate.persistence.jooq.tables.GlobalLock;
import javax.annotation.Generated;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

/** A class modelling indexes of tables of the <code></code> schema. */
@Generated(
    value = {"http://www.jooq.org", "jOOQ version:3.11.12"},
    comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX =
      Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
  public static final Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY;
  public static final Index GLOBAL_LOCK_IDX_KEY = Indexes0.GLOBAL_LOCK_IDX_KEY;
  public static final Index GLOBAL_LOCK_PRIMARY = Indexes0.GLOBAL_LOCK_PRIMARY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {
    public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX =
        Internal.createIndex(
            "flyway_schema_history_s_idx",
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            new OrderField[] {FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS},
            false);
    public static Index FLYWAY_SCHEMA_HISTORY_PRIMARY =
        Internal.createIndex(
            "PRIMARY",
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            new OrderField[] {FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK},
            true);
    public static Index GLOBAL_LOCK_IDX_KEY =
        Internal.createIndex(
            "idx_key", GlobalLock.GLOBAL_LOCK, new OrderField[] {GlobalLock.GLOBAL_LOCK.KEY}, true);
    public static Index GLOBAL_LOCK_PRIMARY =
        Internal.createIndex(
            "PRIMARY", GlobalLock.GLOBAL_LOCK, new OrderField[] {GlobalLock.GLOBAL_LOCK.ID}, true);
  }
}
