name: SonarScan

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  sonarscan:
    name: SonarScan
    runs-on: self-hosted
    steps:
      - name: sonarscan
        run: |
          echo "sonar scanning start..."
          set -ex && sonar-scanner \
            -Dsonar.projectKey=auro \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:10318 \
            -Dsonar.login=sqp_da7281e7364bb0fa4f24f0171af7cf2d46bd9290
          echo "sonar scanning end."
