// Code generated by github.com/sylvan/auro/toolkits/cmd/gen-grpc. DO NOT EDIT.
package assoc

import (
	"path"
	"reflect"
)

type empty struct {
}

func getPkgName() string {
	return path.Base(reflect.TypeOf(empty{}).PkgPath())
}
